// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PharmaDocs.Infrastructure.Data;

#nullable disable

namespace PharmaDocs.Infrastructure.Migrations
{
    [DbContext(typeof(PharmaDocsDbContext))]
    [Migration("20260515230853_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PharmaDocs.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionPackageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("SubmissionPackageId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.DocumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProductId");

                    b.ToTable("DocumentRecords");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("DIN")
                        .HasColumnType("text");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicinalIngredient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NPN")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteOfAdministration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TherapeuticCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.SubmissionDocument", b =>
                {
                    b.Property<Guid>("SubmissionPackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubmissionPackageId", "DocumentRecordId");

                    b.HasIndex("DocumentRecordId");

                    b.ToTable("SubmissionDocuments");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.SubmissionPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegulatoryBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("SubmissionDate")
                        .HasColumnType("date");

                    b.Property<string>("SubmissionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProductId");

                    b.ToTable("SubmissionPackages");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("PharmaDocs.Domain.Entities.User", "ChangedBy")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaDocs.Domain.Entities.SubmissionPackage", "SubmissionPackage")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SubmissionPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("SubmissionPackage");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.DocumentRecord", b =>
                {
                    b.HasOne("PharmaDocs.Domain.Entities.User", "CreatedBy")
                        .WithMany("DocumentRecords")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaDocs.Domain.Entities.Product", "Product")
                        .WithMany("Documents")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.Product", b =>
                {
                    b.HasOne("PharmaDocs.Domain.Entities.User", "CreatedBy")
                        .WithMany("Products")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.SubmissionDocument", b =>
                {
                    b.HasOne("PharmaDocs.Domain.Entities.DocumentRecord", "DocumentRecord")
                        .WithMany("SubmissionDocuments")
                        .HasForeignKey("DocumentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaDocs.Domain.Entities.SubmissionPackage", "SubmissionPackage")
                        .WithMany("SubmissionDocuments")
                        .HasForeignKey("SubmissionPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentRecord");

                    b.Navigation("SubmissionPackage");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.SubmissionPackage", b =>
                {
                    b.HasOne("PharmaDocs.Domain.Entities.User", "CreatedBy")
                        .WithMany("SubmissionPackages")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaDocs.Domain.Entities.Product", "Product")
                        .WithMany("SubmissionPackages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.DocumentRecord", b =>
                {
                    b.Navigation("SubmissionDocuments");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.Product", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("SubmissionPackages");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.SubmissionPackage", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("SubmissionDocuments");
                });

            modelBuilder.Entity("PharmaDocs.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("DocumentRecords");

                    b.Navigation("Products");

                    b.Navigation("SubmissionPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
